<h1 style = "color: blue"> Python Libraries and Data Processing <h1>

In [3]:
import sys

print("Python Version:", sys.version)

Python Version: 3.13.9 (tags/v3.13.9:8183fa5, Oct 14 2025, 14:09:13) [MSC v.1944 64 bit (AMD64)]


# NumPy Library

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.5


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Array type:", type(arr))

Array: [1 2 3 4 5]
Array type: <class 'numpy.ndarray'>


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)
print("Array b:", a*2)

Array a: [1 2 3 4 5]
Array b: [ 2  4  6  8 10]


In [11]:
import numpy as np

arr_1 = np.array([5, 10, 12, 16])
arr_2 = np.array([2, 5, 4, 8])

sum_arr = arr_1 + arr_2
print("Sum of arrays:", sum_arr)

diff_arr = arr_1 - arr_2
print("Difference of arrays:", diff_arr)

prod_arr = arr_1 * arr_2
print("Product of arrays:", prod_arr)

div_arr = arr_1 / arr_2
print("Division of arrays:", div_arr)

Sum of arrays: [ 7 15 16 24]
Difference of arrays: [3 5 8 8]
Product of arrays: [ 10  50  48 128]
Division of arrays: [2.5 2.  3.  2. ]


In [ ]:
import numpy as np

arr_1 = np.array([5, 10, 12, 16])
arr_2 = np.array([2, 5, 4, 8])

result_addition = np.add(arr_1, arr_2)
print("Result of addition:", result_addition)

result_subtraction = np.subtract(arr_1, arr_2)
print("Result of subtraction:", result_subtraction)

result_multiplication = np.multiply(arr_1, arr_2)
print("Result of multiplication:", result_multiplication)

result_division = np.divide(arr_1, arr_2)
print("Result of division:", result_division)

Result of addition: [ 7 15 16 24]
Result of subtraction: [3 5 8 8]
Result of multiplication: [ 10  50  48 128]
Result of division: [2.5 2.  3.  2. ]


In [ ]:
import numpy as np

arr = np.array([16, 9, 25, 64])
sqrt_arr = np.sqrt(arr)
print("Square root of array elements:", sqrt_arr)


Square root of array elements: [4. 3. 5. 8.]


In [16]:
import numpy as np

arr = np.array([16, 9, 25, 64])

max_arr = np.max(arr)
print("Maximum value in the array:", max_arr)

min_arr = np.min(arr)
print("Minimum value in the array:", min_arr)

sum_arr = np.sum(arr)
print("Sum of all elements in the array:", sum_arr)

mean_arr = np.mean(arr)
print("Mean of the array elements:", mean_arr)

Maximum value in the array: 64
Minimum value in the array: 9
Sum of all elements in the array: 114
Mean of the array elements: 28.5


Multidimensional Array

In [ ]:
# 2D Array

import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d) # Two rows and three columns

2D Array:
 [[1 2 3]
 [4 5 6]]


In [31]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# arr_2d.shape
print("Shape of the 2D array:", arr_2d.shape)

# arr_2d.ndim
print("Number of dimensions of the 2D array:", arr_2d.ndim)

# arr_2d.size
print("Total number of elements in the 2D array:", arr_2d.size)

Shape of the 2D array: (2, 3)
Number of dimensions of the 2D array: 2
Total number of elements in the 2D array: 6


In [36]:
import numpy as np

arr_2d = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

# arr_2d.shape
print("Shape of the 2D array:", arr_2d.shape)

# arr_2d.ndim
print("Number of dimensions of the 2D array:", arr_2d.ndim)

# arr_2d.size
print("Total number of elements in the 2D array:", arr_2d.size)

Shape of the 2D array: (3, 3)
Number of dimensions of the 2D array: 2
Total number of elements in the 2D array: 9


In [29]:
import numpy as np

arr_2d = np.array([
    [[1, 2], [3, 4], [5, 6]], 
    [[7, 8], [9, 10], [11, 12]], 
    [[13, 14], [15, 16], [17, 18]]
])

# arr_3d.shape
print("Shape of the 3D array:", arr_2d.shape) # (3, 3, 2)

# arr_3d.ndim
print("Number of dimensions of the 3D array:", arr_2d.ndim)

# arr_3d.size
print("Total number of elements in the 3D array:", arr_2d.size)

Shape of the 3D array: (3, 3, 2)
Number of dimensions of the 3D array: 3
Total number of elements in the 3D array: 18


In [35]:
arr = np.array([[6, 4, 8], [4, 5, 8]])

print(arr[0, 2])

8


In [39]:
import numpy as np

arr_2d = np.array([
    [[1, 2], [3, 4], [5, 6]], 
    [[7, 8], [10, 11], [13, 14]], 
    [[2, 3], [5, 6], [8, 9]]
])

print(arr_2d[1, 2, 1])
print(arr_2d[-2, -1, -1])

print(arr_2d[2, 1, 0])
print(arr_2d[-1, -2, -2])

14
14
5
5


Boolean Indexing in NumPy

In [3]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

condition = arr > 20
print("Condition (arr > 25):", condition)

filtered_arr = arr[condition]
print("Filtered array (elements > 20):", filtered_arr)

Condition (arr > 25): [False False  True  True  True]
Filtered array (elements > 20): [30 40 50]


In [8]:
import numpy as np

arr = np.array([12, 18, 22, 19, 30])

# 15 < arr < 20
condition = (arr > 15) & (arr < 20)
print("Condition (15 < arr < 20):", condition)

filtered_arr = arr[condition]
print("Filtered array (15 < elements < 20):", filtered_arr)

print(arr[(arr > 15) & (arr < 20)])

Condition (15 < arr < 20): [False  True False  True False]
Filtered array (15 < elements < 20): [18 19]
[18 19]


Extract all elements that are 
* Grater than 10 or less than 5
* and not equal to 50

In [14]:
import numpy as np

arr = np.array([
    [12, 5, 7, 20],
    [3, 15, 8, 2],
    [10, 25, 6, 18],
    [4, 11, 30, 9]
])

condition = ((arr > 10) | (arr < 5)) & (arr != 15)
print("Condition ((arr > 10) | (arr < 5)) & (arr != 15):", condition)

filtered_arr = arr[condition]
print("Filtered array (elements > 10 or < 5 and != 15):", filtered_arr)

print("Filtered array using direct indexing:")

arr_filtered = arr [((arr > 10) | (arr < 5)) & (arr != 15)]
print(arr_filtered) 

Condition ((arr > 10) | (arr < 5)) & (arr != 15): [[ True False False  True]
 [ True False False  True]
 [False  True False  True]
 [ True  True  True False]]
Filtered array (elements > 10 or < 5 and != 15): [12 20  3  2 25 18  4 11 30]
Filtered array using direct indexing:
[12 20  3  2 25 18  4 11 30]


Array Initialization

In [20]:
import numpy as np

arr_zero = np.zeros((3, 4))
print("Array of zeros:\n", arr_zero)

Array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
import numpy as np

arr_full = np.full((2, 3), 7)
print("Array filled with 7:\n", arr_full)

Array filled with 7:
 [[7 7 7]
 [7 7 7]]


In [24]:
import numpy as np

arr_empty = np.empty((2, 3))
print("Array with uninitialized values:\n", arr_empty) # memory garbage values

arr_e = np.empty([2, 3])
print("Array with uninitialized values:\n", arr_e) # memory garbage values

Array with uninitialized values:
 [[1.00627338e-070 4.39027223e+175 4.42322606e-062]
 [1.73735280e-047 0.00000000e+000 3.25060610e-319]]
Array with uninitialized values:
 [[1.00627338e-070 4.39027223e+175 4.42322606e-062]
 [1.73735280e-047 0.00000000e+000 3.25060610e-319]]


# Pandas Library

In [25]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 2.3.3


In [28]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24 , 27, 22, 32]
    }

df = pd.DataFrame(data)
print("DataFrame:\n", df)

DataFrame:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32


In [43]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24 , 27, 22, 32]
    }

df = pd.DataFrame(data)
df.loc[1]

Name    Bob
Age      27
Name: 1, dtype: object

In [41]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24 , 27, 35, 32]
    }

df = pd.DataFrame(data)

print(df.loc[2, 'Age'])

35


In [50]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24 , 27, 35, 40]
    }

df = pd.DataFrame(data)

df.iloc[3]

Name    David
Age        40
Name: 3, dtype: object

In [49]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24 , 27, 35, 40]
    }

df = pd.DataFrame(data)

print(df.iloc[3, 1])

40


In [1]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print("DataFrame:\n", df)

DataFrame:
       calories  duration
day1       420        50
day2       380        40
day3       390        45


In [8]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df.loc["day3"])
print("Calories on day3:", df.loc["day3", "duration"])

calories    390
duration     45
Name: day3, dtype: int64
Calories on day3: 45


In [11]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df.loc[["day1", "day3"]])

      calories  duration
day1       420        50
day3       390        45


In [ ]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

print(df.shape)
print(df.size)

print(list(df.columns))

      calories  duration
day1       420        50
day2       380        40
day3       390        45
(3, 2)
6
['calories', 'duration']


In [19]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

arr = df.values
print(arr)
print(type(arr))

[[420  50]
 [380  40]
 [390  45]]
<class 'numpy.ndarray'>


In [26]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df.iloc[-1])

calories    390
duration     45
Name: day3, dtype: int64


In [33]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

shape = df.shape
print("Number of rows:", shape[0])

print("Number of rows:", len(df))


Number of rows: 3
Number of rows: 3


In [36]:
import pandas as pd

data = {
    "calories": [420, 380, 390, 450],
    "duration": [50, 40, 45, 60]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3", "day4"])

print(df.sum())
print(" ")
print(df.mean())
print(" ")
print(df.describe())


calories    1640
duration     195
dtype: int64
 
calories    410.00
duration     48.75
dtype: float64
 
         calories   duration
count    4.000000   4.000000
mean   410.000000  48.750000
std     31.622777   8.539126
min    380.000000  40.000000
25%    387.500000  43.750000
50%    405.000000  47.500000
75%    427.500000  52.500000
max    450.000000  60.000000


In [37]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Alice', 'Bob', 'Charlie', 'David'],
    "Age": [24, 27, 22, 32],
    "Salary": [50000, 60000, 55000, 70000],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

filtered_df = df[df['Age'] > 19]

print("Filtered DataFrame (Age > 19):\n", filtered_df)

Filtered DataFrame (Age > 19):
       Name  Age  Salary         City
0    Alice   24   50000     New York
1      Bob   27   60000  Los Angeles
2  Charlie   22   55000      Chicago
3    David   32   70000      Houston


In [41]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Alice', 'Bob', 'Charlie', 'David'],
    "Age": [24, 27, 22, 32],
    "Salary": [50000, 60000, 55000, 70000],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

filtered_df = df[(df['Age'] > 20) & (df['Salary'] > 50000)]

print("Filtered DataFrame (Age > 20 and Salary > 50000):\n", filtered_df)

Filtered DataFrame (Age > 20 and Salary > 50000):
       Name  Age  Salary         City
1      Bob   27   60000  Los Angeles
2  Charlie   22   55000      Chicago
3    David   32   70000      Houston


How to add a new Column

In [43]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Alice', 'Bob', 'Charlie', 'David'],
    "Age": [24, 27, 22, 32],
    "Salary": [50000, 60000, 55000, 70000],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

df["Employee ID"] = [11, 12, 13, 14]

print(df)

      Name  Age  Salary         City  Employee ID
0    Alice   24   50000     New York           11
1      Bob   27   60000  Los Angeles           12
2  Charlie   22   55000      Chicago           13
3    David   32   70000      Houston           14


You are given the folowing pandas data frame cpontaning prouduct sales => 

    df = pd.DataFrame({
        "Proudct": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
        "UnitSold": [12, 50, 34, 20, 40],
        "Price": [120000, 1500, 3500, 25000, 6000],
        "Discount": [0.1, 0.05, 0.08, 0.12, 0.7] #discount as a fraction
    })

* calculate the final price after discount
* calculate the total revenue for each product after discount
* for above part 1 and part 2, you should add both result as new coulm to the data frame
* filter and display only the product where revenue is grater than 500000
* calculate the total revenue of all product combine

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Proudct": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold": [12, 50, 34, 20, 40],
    "Price": [120000, 1500, 3500, 25000, 6000],
    "Discount": [0.1, 0.05, 0.08, 0.12, 0.7]
})

# final price after discount
df["FinalPrice"] = df["Price"] * (1 - df["Discount"])
print("Final Price after discount:\n", df)
print(" ")
print(df["FinalPrice"])
print(" ")

# total revenue for each product after discount
df["Revenue"] = df["UnitSold"] * df["FinalPrice"]
print("Total Revenue for each product after discount:\n", df)
print(" ")
print(df["Revenue"])
print(" ")

# filter and display only the product where revenue is greater than 500000
filtered_df = df[df["Revenue"] > 500000]
print("Filtered DataFrame (Revenue > 500000):\n", filtered_df)
print(" ")

# total revenue of all product combined
total_revenue = df["Revenue"].sum()
print("Total Revenue of all products combined:", total_revenue)

Final Price after discount:
     Proudct  UnitSold   Price  Discount  FinalPrice
0    Laptop        12  120000      0.10    108000.0
1     Mouse        50    1500      0.05      1425.0
2  Keyboard        34    3500      0.08      3220.0
3   Monitor        20   25000      0.12     22000.0
4   Headset        40    6000      0.70      1800.0
 
0    108000.0
1      1425.0
2      3220.0
3     22000.0
4      1800.0
Name: FinalPrice, dtype: float64
 
Total Revenue for each product after discount:
     Proudct  UnitSold   Price  Discount  FinalPrice    Revenue
0    Laptop        12  120000      0.10    108000.0  1296000.0
1     Mouse        50    1500      0.05      1425.0    71250.0
2  Keyboard        34    3500      0.08      3220.0   109480.0
3   Monitor        20   25000      0.12     22000.0   440000.0
4   Headset        40    6000      0.70      1800.0    72000.0
 
0    1296000.0
1      71250.0
2     109480.0
3     440000.0
4      72000.0
Name: Revenue, dtype: float64
 
Filtered DataFram

In [21]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['Alice', 'Bob', 'Charlie', 'David'],
    "Age": [24, 27, 22, 32],
    "Salary": [50000, 60000, 55000, 70000],
    "City": ['New York', 'Los Angeles', 'Chicago', 'Houston']
})

shape = df.shape
df.loc[shape[0]] = ['Kaveen', 29, 65000, 'Galle']

df.loc[len(df)] = ['Dimantha', 22, 85000, 'Colombo']

print(df)

       Name  Age  Salary         City
0     Alice   24   50000     New York
1       Bob   27   60000  Los Angeles
2   Charlie   22   55000      Chicago
3     David   32   70000      Houston
4    Kaveen   29   65000        Galle
5  Dimantha   22   85000      Colombo


Data Manipulation

In [25]:
import pandas as pd

data = ({
    "Name": ['Alice', 'Bob', 'Charlie'],
    "Age": [24, 27, 22]
})

df = pd.DataFrame(data)
print(df)
print(" ")

new_df = df.drop("Age", axis=1)
print(new_df)

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
 
      Name
0    Alice
1      Bob
2  Charlie


In [29]:
import pandas as pd

data = ({
    "Name": ['Alice', 'Bob', 'Charlie'],
    "Age": [24, 27, 22]
})

df = pd.DataFrame(data)
print(df)
print(" ")

new_df = df.drop(1, axis=0)
print(new_df)

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
 
      Name  Age
0    Alice   24
2  Charlie   22


In [32]:
import pandas as pd

df = pd.read_csv("file_handling/person_data.csv")

print(df)
print(type(df))

   Name  Age    Country      City
0  Alex   16  Sri Lanka   Colombo
1   Mia   17  Australia    Sydney
2  Ravi   15        USA  New York
3  Sara   16         UK    London
4  Liam   17     Canada   Toronto
<class 'pandas.core.frame.DataFrame'>


In [33]:
import pandas as pd

df = pd.read_json("file_handling/my_data.json")

print(df)
print(type(df))

              name  age      city  is_student  courses
0  Tharindu Shehan   39  Galkissa       False     Math
1  Tharindu Shehan   39  Galkissa       False  Science
2  Tharindu Shehan   39  Galkissa       False  History
<class 'pandas.core.frame.DataFrame'>
